// automatically generated by the FlatBuffers compiler, do not modify

package com.tistory.hskimsky.mapreduce.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class YellowFlat extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static YellowFlat getRootAsYellowFlat(ByteBuffer _bb) { return getRootAsYellowFlat(_bb, new YellowFlat()); }
  public static YellowFlat getRootAsYellowFlat(ByteBuffer _bb, YellowFlat obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public YellowFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String vendorID() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer vendorIDAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer vendorIDInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String tpepPickupDatetime() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tpepPickupDatetimeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer tpepPickupDatetimeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String tpepDropoffDatetime() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tpepDropoffDatetimeAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer tpepDropoffDatetimeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public int passengerCount() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public float tripDistance() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public String rateCodeID() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer rateCodeIDAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer rateCodeIDInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String storeAndFwdFlag() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer storeAndFwdFlagAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer storeAndFwdFlagInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public String puLocationID() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer puLocationIDAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer puLocationIDInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String doLocationID() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer doLocationIDAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer doLocationIDInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public String paymentType() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer paymentTypeAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public ByteBuffer paymentTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 22, 1); }
  public float fareAmount() { int o = __offset(24); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float extra() { int o = __offset(26); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float mtaTax() { int o = __offset(28); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float tipAmount() { int o = __offset(30); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float tollsAmount() { int o = __offset(32); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float improvementSurcharge() { int o = __offset(34); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float totalAmount() { int o = __offset(36); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float congestionSurcharge() { int o = __offset(38); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createYellowFlat(FlatBufferBuilder builder,
      int vendorIDOffset,
      int tpepPickupDatetimeOffset,
      int tpepDropoffDatetimeOffset,
      int passengerCount,
      float tripDistance,
      int rateCodeIDOffset,
      int storeAndFwdFlagOffset,
      int puLocationIDOffset,
      int doLocationIDOffset,
      int paymentTypeOffset,
      float fareAmount,
      float extra,
      float mtaTax,
      float tipAmount,
      float tollsAmount,
      float improvementSurcharge,
      float totalAmount,
      float congestionSurcharge) {
    builder.startTable(18);
    YellowFlat.addCongestionSurcharge(builder, congestionSurcharge);
    YellowFlat.addTotalAmount(builder, totalAmount);
    YellowFlat.addImprovementSurcharge(builder, improvementSurcharge);
    YellowFlat.addTollsAmount(builder, tollsAmount);
    YellowFlat.addTipAmount(builder, tipAmount);
    YellowFlat.addMtaTax(builder, mtaTax);
    YellowFlat.addExtra(builder, extra);
    YellowFlat.addFareAmount(builder, fareAmount);
    YellowFlat.addPaymentType(builder, paymentTypeOffset);
    YellowFlat.addDoLocationID(builder, doLocationIDOffset);
    YellowFlat.addPuLocationID(builder, puLocationIDOffset);
    YellowFlat.addStoreAndFwdFlag(builder, storeAndFwdFlagOffset);
    YellowFlat.addRateCodeID(builder, rateCodeIDOffset);
    YellowFlat.addTripDistance(builder, tripDistance);
    YellowFlat.addPassengerCount(builder, passengerCount);
    YellowFlat.addTpepDropoffDatetime(builder, tpepDropoffDatetimeOffset);
    YellowFlat.addTpepPickupDatetime(builder, tpepPickupDatetimeOffset);
    YellowFlat.addVendorID(builder, vendorIDOffset);
    return YellowFlat.endYellowFlat(builder);
  }

  public static void startYellowFlat(FlatBufferBuilder builder) { builder.startTable(18); }
  public static void addVendorID(FlatBufferBuilder builder, int vendorIDOffset) { builder.addOffset(0, vendorIDOffset, 0); }
  public static void addTpepPickupDatetime(FlatBufferBuilder builder, int tpepPickupDatetimeOffset) { builder.addOffset(1, tpepPickupDatetimeOffset, 0); }
  public static void addTpepDropoffDatetime(FlatBufferBuilder builder, int tpepDropoffDatetimeOffset) { builder.addOffset(2, tpepDropoffDatetimeOffset, 0); }
  public static void addPassengerCount(FlatBufferBuilder builder, int passengerCount) { builder.addInt(3, passengerCount, 0); }
  public static void addTripDistance(FlatBufferBuilder builder, float tripDistance) { builder.addFloat(4, tripDistance, 0.0f); }
  public static void addRateCodeID(FlatBufferBuilder builder, int rateCodeIDOffset) { builder.addOffset(5, rateCodeIDOffset, 0); }
  public static void addStoreAndFwdFlag(FlatBufferBuilder builder, int storeAndFwdFlagOffset) { builder.addOffset(6, storeAndFwdFlagOffset, 0); }
  public static void addPuLocationID(FlatBufferBuilder builder, int puLocationIDOffset) { builder.addOffset(7, puLocationIDOffset, 0); }
  public static void addDoLocationID(FlatBufferBuilder builder, int doLocationIDOffset) { builder.addOffset(8, doLocationIDOffset, 0); }
  public static void addPaymentType(FlatBufferBuilder builder, int paymentTypeOffset) { builder.addOffset(9, paymentTypeOffset, 0); }
  public static void addFareAmount(FlatBufferBuilder builder, float fareAmount) { builder.addFloat(10, fareAmount, 0.0f); }
  public static void addExtra(FlatBufferBuilder builder, float extra) { builder.addFloat(11, extra, 0.0f); }
  public static void addMtaTax(FlatBufferBuilder builder, float mtaTax) { builder.addFloat(12, mtaTax, 0.0f); }
  public static void addTipAmount(FlatBufferBuilder builder, float tipAmount) { builder.addFloat(13, tipAmount, 0.0f); }
  public static void addTollsAmount(FlatBufferBuilder builder, float tollsAmount) { builder.addFloat(14, tollsAmount, 0.0f); }
  public static void addImprovementSurcharge(FlatBufferBuilder builder, float improvementSurcharge) { builder.addFloat(15, improvementSurcharge, 0.0f); }
  public static void addTotalAmount(FlatBufferBuilder builder, float totalAmount) { builder.addFloat(16, totalAmount, 0.0f); }
  public static void addCongestionSurcharge(FlatBufferBuilder builder, float congestionSurcharge) { builder.addFloat(17, congestionSurcharge, 0.0f); }
  public static int endYellowFlat(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishYellowFlatBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedYellowFlatBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public YellowFlat get(int j) { return get(new YellowFlat(), j); }
    public YellowFlat get(YellowFlat obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

