// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Yellow.proto

package com.tistory.hskimsky.mapreduce.protobuf;

public final class YellowProto {
  private YellowProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface YellowOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string vendorID = 1;
    /**
     * <code>optional string vendorID = 1;</code>
     */
    boolean hasVendorID();
    /**
     * <code>optional string vendorID = 1;</code>
     */
    java.lang.String getVendorID();
    /**
     * <code>optional string vendorID = 1;</code>
     */
    com.google.protobuf.ByteString
        getVendorIDBytes();

    // optional string tpepPickupDatetime = 2;
    /**
     * <code>optional string tpepPickupDatetime = 2;</code>
     */
    boolean hasTpepPickupDatetime();
    /**
     * <code>optional string tpepPickupDatetime = 2;</code>
     */
    java.lang.String getTpepPickupDatetime();
    /**
     * <code>optional string tpepPickupDatetime = 2;</code>
     */
    com.google.protobuf.ByteString
        getTpepPickupDatetimeBytes();

    // optional string tpepDropoffDatetime = 3;
    /**
     * <code>optional string tpepDropoffDatetime = 3;</code>
     */
    boolean hasTpepDropoffDatetime();
    /**
     * <code>optional string tpepDropoffDatetime = 3;</code>
     */
    java.lang.String getTpepDropoffDatetime();
    /**
     * <code>optional string tpepDropoffDatetime = 3;</code>
     */
    com.google.protobuf.ByteString
        getTpepDropoffDatetimeBytes();

    // optional int32 passengerCount = 4;
    /**
     * <code>optional int32 passengerCount = 4;</code>
     */
    boolean hasPassengerCount();
    /**
     * <code>optional int32 passengerCount = 4;</code>
     */
    int getPassengerCount();

    // optional float tripDistance = 5;
    /**
     * <code>optional float tripDistance = 5;</code>
     */
    boolean hasTripDistance();
    /**
     * <code>optional float tripDistance = 5;</code>
     */
    float getTripDistance();

    // optional string rateCodeID = 6;
    /**
     * <code>optional string rateCodeID = 6;</code>
     */
    boolean hasRateCodeID();
    /**
     * <code>optional string rateCodeID = 6;</code>
     */
    java.lang.String getRateCodeID();
    /**
     * <code>optional string rateCodeID = 6;</code>
     */
    com.google.protobuf.ByteString
        getRateCodeIDBytes();

    // optional string storeAndFwdFlag = 7;
    /**
     * <code>optional string storeAndFwdFlag = 7;</code>
     */
    boolean hasStoreAndFwdFlag();
    /**
     * <code>optional string storeAndFwdFlag = 7;</code>
     */
    java.lang.String getStoreAndFwdFlag();
    /**
     * <code>optional string storeAndFwdFlag = 7;</code>
     */
    com.google.protobuf.ByteString
        getStoreAndFwdFlagBytes();

    // optional string puLocationID = 8;
    /**
     * <code>optional string puLocationID = 8;</code>
     */
    boolean hasPuLocationID();
    /**
     * <code>optional string puLocationID = 8;</code>
     */
    java.lang.String getPuLocationID();
    /**
     * <code>optional string puLocationID = 8;</code>
     */
    com.google.protobuf.ByteString
        getPuLocationIDBytes();

    // optional string doLocationID = 9;
    /**
     * <code>optional string doLocationID = 9;</code>
     */
    boolean hasDoLocationID();
    /**
     * <code>optional string doLocationID = 9;</code>
     */
    java.lang.String getDoLocationID();
    /**
     * <code>optional string doLocationID = 9;</code>
     */
    com.google.protobuf.ByteString
        getDoLocationIDBytes();

    // optional string paymentType = 10;
    /**
     * <code>optional string paymentType = 10;</code>
     */
    boolean hasPaymentType();
    /**
     * <code>optional string paymentType = 10;</code>
     */
    java.lang.String getPaymentType();
    /**
     * <code>optional string paymentType = 10;</code>
     */
    com.google.protobuf.ByteString
        getPaymentTypeBytes();

    // optional float fareAmount = 11;
    /**
     * <code>optional float fareAmount = 11;</code>
     */
    boolean hasFareAmount();
    /**
     * <code>optional float fareAmount = 11;</code>
     */
    float getFareAmount();

    // optional float extra = 12;
    /**
     * <code>optional float extra = 12;</code>
     */
    boolean hasExtra();
    /**
     * <code>optional float extra = 12;</code>
     */
    float getExtra();

    // optional float mtaTax = 13;
    /**
     * <code>optional float mtaTax = 13;</code>
     */
    boolean hasMtaTax();
    /**
     * <code>optional float mtaTax = 13;</code>
     */
    float getMtaTax();

    // optional float tipAmount = 14;
    /**
     * <code>optional float tipAmount = 14;</code>
     */
    boolean hasTipAmount();
    /**
     * <code>optional float tipAmount = 14;</code>
     */
    float getTipAmount();

    // optional float tollsAmount = 15;
    /**
     * <code>optional float tollsAmount = 15;</code>
     */
    boolean hasTollsAmount();
    /**
     * <code>optional float tollsAmount = 15;</code>
     */
    float getTollsAmount();

    // optional float improvementSurcharge = 16;
    /**
     * <code>optional float improvementSurcharge = 16;</code>
     */
    boolean hasImprovementSurcharge();
    /**
     * <code>optional float improvementSurcharge = 16;</code>
     */
    float getImprovementSurcharge();

    // optional float totalAmount = 17;
    /**
     * <code>optional float totalAmount = 17;</code>
     */
    boolean hasTotalAmount();
    /**
     * <code>optional float totalAmount = 17;</code>
     */
    float getTotalAmount();

    // optional float congestionSurcharge = 18;
    /**
     * <code>optional float congestionSurcharge = 18;</code>
     */
    boolean hasCongestionSurcharge();
    /**
     * <code>optional float congestionSurcharge = 18;</code>
     */
    float getCongestionSurcharge();
  }
  /**
   * Protobuf type {@code com.tistory.hskimsky.mapreduce.protobuf.Yellow}
   */
  public static final class Yellow extends
      com.google.protobuf.GeneratedMessage
      implements YellowOrBuilder {
    // Use Yellow.newBuilder() to construct.
    private Yellow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Yellow(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Yellow defaultInstance;
    public static Yellow getDefaultInstance() {
      return defaultInstance;
    }

    public Yellow getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Yellow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              vendorID_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              tpepPickupDatetime_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              tpepDropoffDatetime_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              passengerCount_ = input.readInt32();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              tripDistance_ = input.readFloat();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              rateCodeID_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              storeAndFwdFlag_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              puLocationID_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              doLocationID_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              paymentType_ = input.readBytes();
              break;
            }
            case 93: {
              bitField0_ |= 0x00000400;
              fareAmount_ = input.readFloat();
              break;
            }
            case 101: {
              bitField0_ |= 0x00000800;
              extra_ = input.readFloat();
              break;
            }
            case 109: {
              bitField0_ |= 0x00001000;
              mtaTax_ = input.readFloat();
              break;
            }
            case 117: {
              bitField0_ |= 0x00002000;
              tipAmount_ = input.readFloat();
              break;
            }
            case 125: {
              bitField0_ |= 0x00004000;
              tollsAmount_ = input.readFloat();
              break;
            }
            case 133: {
              bitField0_ |= 0x00008000;
              improvementSurcharge_ = input.readFloat();
              break;
            }
            case 141: {
              bitField0_ |= 0x00010000;
              totalAmount_ = input.readFloat();
              break;
            }
            case 149: {
              bitField0_ |= 0x00020000;
              congestionSurcharge_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tistory.hskimsky.mapreduce.protobuf.YellowProto.internal_static_com_tistory_hskimsky_mapreduce_protobuf_Yellow_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tistory.hskimsky.mapreduce.protobuf.YellowProto.internal_static_com_tistory_hskimsky_mapreduce_protobuf_Yellow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow.class, com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow.Builder.class);
    }

    public static com.google.protobuf.Parser<Yellow> PARSER =
        new com.google.protobuf.AbstractParser<Yellow>() {
      public Yellow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Yellow(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Yellow> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string vendorID = 1;
    public static final int VENDORID_FIELD_NUMBER = 1;
    private java.lang.Object vendorID_;
    /**
     * <code>optional string vendorID = 1;</code>
     */
    public boolean hasVendorID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string vendorID = 1;</code>
     */
    public java.lang.String getVendorID() {
      java.lang.Object ref = vendorID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vendorID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string vendorID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVendorIDBytes() {
      java.lang.Object ref = vendorID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vendorID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string tpepPickupDatetime = 2;
    public static final int TPEPPICKUPDATETIME_FIELD_NUMBER = 2;
    private java.lang.Object tpepPickupDatetime_;
    /**
     * <code>optional string tpepPickupDatetime = 2;</code>
     */
    public boolean hasTpepPickupDatetime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string tpepPickupDatetime = 2;</code>
     */
    public java.lang.String getTpepPickupDatetime() {
      java.lang.Object ref = tpepPickupDatetime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tpepPickupDatetime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tpepPickupDatetime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTpepPickupDatetimeBytes() {
      java.lang.Object ref = tpepPickupDatetime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tpepPickupDatetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string tpepDropoffDatetime = 3;
    public static final int TPEPDROPOFFDATETIME_FIELD_NUMBER = 3;
    private java.lang.Object tpepDropoffDatetime_;
    /**
     * <code>optional string tpepDropoffDatetime = 3;</code>
     */
    public boolean hasTpepDropoffDatetime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string tpepDropoffDatetime = 3;</code>
     */
    public java.lang.String getTpepDropoffDatetime() {
      java.lang.Object ref = tpepDropoffDatetime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tpepDropoffDatetime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tpepDropoffDatetime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTpepDropoffDatetimeBytes() {
      java.lang.Object ref = tpepDropoffDatetime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tpepDropoffDatetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 passengerCount = 4;
    public static final int PASSENGERCOUNT_FIELD_NUMBER = 4;
    private int passengerCount_;
    /**
     * <code>optional int32 passengerCount = 4;</code>
     */
    public boolean hasPassengerCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 passengerCount = 4;</code>
     */
    public int getPassengerCount() {
      return passengerCount_;
    }

    // optional float tripDistance = 5;
    public static final int TRIPDISTANCE_FIELD_NUMBER = 5;
    private float tripDistance_;
    /**
     * <code>optional float tripDistance = 5;</code>
     */
    public boolean hasTripDistance() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float tripDistance = 5;</code>
     */
    public float getTripDistance() {
      return tripDistance_;
    }

    // optional string rateCodeID = 6;
    public static final int RATECODEID_FIELD_NUMBER = 6;
    private java.lang.Object rateCodeID_;
    /**
     * <code>optional string rateCodeID = 6;</code>
     */
    public boolean hasRateCodeID() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string rateCodeID = 6;</code>
     */
    public java.lang.String getRateCodeID() {
      java.lang.Object ref = rateCodeID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rateCodeID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string rateCodeID = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRateCodeIDBytes() {
      java.lang.Object ref = rateCodeID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rateCodeID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string storeAndFwdFlag = 7;
    public static final int STOREANDFWDFLAG_FIELD_NUMBER = 7;
    private java.lang.Object storeAndFwdFlag_;
    /**
     * <code>optional string storeAndFwdFlag = 7;</code>
     */
    public boolean hasStoreAndFwdFlag() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string storeAndFwdFlag = 7;</code>
     */
    public java.lang.String getStoreAndFwdFlag() {
      java.lang.Object ref = storeAndFwdFlag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          storeAndFwdFlag_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string storeAndFwdFlag = 7;</code>
     */
    public com.google.protobuf.ByteString
        getStoreAndFwdFlagBytes() {
      java.lang.Object ref = storeAndFwdFlag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storeAndFwdFlag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string puLocationID = 8;
    public static final int PULOCATIONID_FIELD_NUMBER = 8;
    private java.lang.Object puLocationID_;
    /**
     * <code>optional string puLocationID = 8;</code>
     */
    public boolean hasPuLocationID() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string puLocationID = 8;</code>
     */
    public java.lang.String getPuLocationID() {
      java.lang.Object ref = puLocationID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          puLocationID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string puLocationID = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPuLocationIDBytes() {
      java.lang.Object ref = puLocationID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        puLocationID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string doLocationID = 9;
    public static final int DOLOCATIONID_FIELD_NUMBER = 9;
    private java.lang.Object doLocationID_;
    /**
     * <code>optional string doLocationID = 9;</code>
     */
    public boolean hasDoLocationID() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string doLocationID = 9;</code>
     */
    public java.lang.String getDoLocationID() {
      java.lang.Object ref = doLocationID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          doLocationID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string doLocationID = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDoLocationIDBytes() {
      java.lang.Object ref = doLocationID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        doLocationID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string paymentType = 10;
    public static final int PAYMENTTYPE_FIELD_NUMBER = 10;
    private java.lang.Object paymentType_;
    /**
     * <code>optional string paymentType = 10;</code>
     */
    public boolean hasPaymentType() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string paymentType = 10;</code>
     */
    public java.lang.String getPaymentType() {
      java.lang.Object ref = paymentType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          paymentType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string paymentType = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPaymentTypeBytes() {
      java.lang.Object ref = paymentType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional float fareAmount = 11;
    public static final int FAREAMOUNT_FIELD_NUMBER = 11;
    private float fareAmount_;
    /**
     * <code>optional float fareAmount = 11;</code>
     */
    public boolean hasFareAmount() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional float fareAmount = 11;</code>
     */
    public float getFareAmount() {
      return fareAmount_;
    }

    // optional float extra = 12;
    public static final int EXTRA_FIELD_NUMBER = 12;
    private float extra_;
    /**
     * <code>optional float extra = 12;</code>
     */
    public boolean hasExtra() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional float extra = 12;</code>
     */
    public float getExtra() {
      return extra_;
    }

    // optional float mtaTax = 13;
    public static final int MTATAX_FIELD_NUMBER = 13;
    private float mtaTax_;
    /**
     * <code>optional float mtaTax = 13;</code>
     */
    public boolean hasMtaTax() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional float mtaTax = 13;</code>
     */
    public float getMtaTax() {
      return mtaTax_;
    }

    // optional float tipAmount = 14;
    public static final int TIPAMOUNT_FIELD_NUMBER = 14;
    private float tipAmount_;
    /**
     * <code>optional float tipAmount = 14;</code>
     */
    public boolean hasTipAmount() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional float tipAmount = 14;</code>
     */
    public float getTipAmount() {
      return tipAmount_;
    }

    // optional float tollsAmount = 15;
    public static final int TOLLSAMOUNT_FIELD_NUMBER = 15;
    private float tollsAmount_;
    /**
     * <code>optional float tollsAmount = 15;</code>
     */
    public boolean hasTollsAmount() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional float tollsAmount = 15;</code>
     */
    public float getTollsAmount() {
      return tollsAmount_;
    }

    // optional float improvementSurcharge = 16;
    public static final int IMPROVEMENTSURCHARGE_FIELD_NUMBER = 16;
    private float improvementSurcharge_;
    /**
     * <code>optional float improvementSurcharge = 16;</code>
     */
    public boolean hasImprovementSurcharge() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional float improvementSurcharge = 16;</code>
     */
    public float getImprovementSurcharge() {
      return improvementSurcharge_;
    }

    // optional float totalAmount = 17;
    public static final int TOTALAMOUNT_FIELD_NUMBER = 17;
    private float totalAmount_;
    /**
     * <code>optional float totalAmount = 17;</code>
     */
    public boolean hasTotalAmount() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional float totalAmount = 17;</code>
     */
    public float getTotalAmount() {
      return totalAmount_;
    }

    // optional float congestionSurcharge = 18;
    public static final int CONGESTIONSURCHARGE_FIELD_NUMBER = 18;
    private float congestionSurcharge_;
    /**
     * <code>optional float congestionSurcharge = 18;</code>
     */
    public boolean hasCongestionSurcharge() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional float congestionSurcharge = 18;</code>
     */
    public float getCongestionSurcharge() {
      return congestionSurcharge_;
    }

    private void initFields() {
      vendorID_ = "";
      tpepPickupDatetime_ = "";
      tpepDropoffDatetime_ = "";
      passengerCount_ = 0;
      tripDistance_ = 0F;
      rateCodeID_ = "";
      storeAndFwdFlag_ = "";
      puLocationID_ = "";
      doLocationID_ = "";
      paymentType_ = "";
      fareAmount_ = 0F;
      extra_ = 0F;
      mtaTax_ = 0F;
      tipAmount_ = 0F;
      tollsAmount_ = 0F;
      improvementSurcharge_ = 0F;
      totalAmount_ = 0F;
      congestionSurcharge_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVendorIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTpepPickupDatetimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTpepDropoffDatetimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, passengerCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, tripDistance_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getRateCodeIDBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getStoreAndFwdFlagBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getPuLocationIDBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getDoLocationIDBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getPaymentTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeFloat(11, fareAmount_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeFloat(12, extra_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeFloat(13, mtaTax_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeFloat(14, tipAmount_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeFloat(15, tollsAmount_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeFloat(16, improvementSurcharge_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeFloat(17, totalAmount_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeFloat(18, congestionSurcharge_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVendorIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTpepPickupDatetimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTpepDropoffDatetimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, passengerCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, tripDistance_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getRateCodeIDBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getStoreAndFwdFlagBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getPuLocationIDBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getDoLocationIDBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getPaymentTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, fareAmount_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, extra_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(13, mtaTax_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(14, tipAmount_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(15, tollsAmount_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(16, improvementSurcharge_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(17, totalAmount_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(18, congestionSurcharge_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tistory.hskimsky.mapreduce.protobuf.Yellow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tistory.hskimsky.mapreduce.protobuf.YellowProto.YellowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tistory.hskimsky.mapreduce.protobuf.YellowProto.internal_static_com_tistory_hskimsky_mapreduce_protobuf_Yellow_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tistory.hskimsky.mapreduce.protobuf.YellowProto.internal_static_com_tistory_hskimsky_mapreduce_protobuf_Yellow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow.class, com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow.Builder.class);
      }

      // Construct using com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        vendorID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tpepPickupDatetime_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tpepDropoffDatetime_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        passengerCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        tripDistance_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        rateCodeID_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        storeAndFwdFlag_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        puLocationID_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        doLocationID_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        paymentType_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        fareAmount_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000400);
        extra_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000800);
        mtaTax_ = 0F;
        bitField0_ = (bitField0_ & ~0x00001000);
        tipAmount_ = 0F;
        bitField0_ = (bitField0_ & ~0x00002000);
        tollsAmount_ = 0F;
        bitField0_ = (bitField0_ & ~0x00004000);
        improvementSurcharge_ = 0F;
        bitField0_ = (bitField0_ & ~0x00008000);
        totalAmount_ = 0F;
        bitField0_ = (bitField0_ & ~0x00010000);
        congestionSurcharge_ = 0F;
        bitField0_ = (bitField0_ & ~0x00020000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tistory.hskimsky.mapreduce.protobuf.YellowProto.internal_static_com_tistory_hskimsky_mapreduce_protobuf_Yellow_descriptor;
      }

      public com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow getDefaultInstanceForType() {
        return com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow.getDefaultInstance();
      }

      public com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow build() {
        com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow buildPartial() {
        com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow result = new com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.vendorID_ = vendorID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tpepPickupDatetime_ = tpepPickupDatetime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tpepDropoffDatetime_ = tpepDropoffDatetime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.passengerCount_ = passengerCount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.tripDistance_ = tripDistance_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.rateCodeID_ = rateCodeID_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.storeAndFwdFlag_ = storeAndFwdFlag_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.puLocationID_ = puLocationID_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.doLocationID_ = doLocationID_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.paymentType_ = paymentType_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.fareAmount_ = fareAmount_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.extra_ = extra_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.mtaTax_ = mtaTax_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.tipAmount_ = tipAmount_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.tollsAmount_ = tollsAmount_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.improvementSurcharge_ = improvementSurcharge_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.totalAmount_ = totalAmount_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.congestionSurcharge_ = congestionSurcharge_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow) {
          return mergeFrom((com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow other) {
        if (other == com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow.getDefaultInstance()) return this;
        if (other.hasVendorID()) {
          bitField0_ |= 0x00000001;
          vendorID_ = other.vendorID_;
          onChanged();
        }
        if (other.hasTpepPickupDatetime()) {
          bitField0_ |= 0x00000002;
          tpepPickupDatetime_ = other.tpepPickupDatetime_;
          onChanged();
        }
        if (other.hasTpepDropoffDatetime()) {
          bitField0_ |= 0x00000004;
          tpepDropoffDatetime_ = other.tpepDropoffDatetime_;
          onChanged();
        }
        if (other.hasPassengerCount()) {
          setPassengerCount(other.getPassengerCount());
        }
        if (other.hasTripDistance()) {
          setTripDistance(other.getTripDistance());
        }
        if (other.hasRateCodeID()) {
          bitField0_ |= 0x00000020;
          rateCodeID_ = other.rateCodeID_;
          onChanged();
        }
        if (other.hasStoreAndFwdFlag()) {
          bitField0_ |= 0x00000040;
          storeAndFwdFlag_ = other.storeAndFwdFlag_;
          onChanged();
        }
        if (other.hasPuLocationID()) {
          bitField0_ |= 0x00000080;
          puLocationID_ = other.puLocationID_;
          onChanged();
        }
        if (other.hasDoLocationID()) {
          bitField0_ |= 0x00000100;
          doLocationID_ = other.doLocationID_;
          onChanged();
        }
        if (other.hasPaymentType()) {
          bitField0_ |= 0x00000200;
          paymentType_ = other.paymentType_;
          onChanged();
        }
        if (other.hasFareAmount()) {
          setFareAmount(other.getFareAmount());
        }
        if (other.hasExtra()) {
          setExtra(other.getExtra());
        }
        if (other.hasMtaTax()) {
          setMtaTax(other.getMtaTax());
        }
        if (other.hasTipAmount()) {
          setTipAmount(other.getTipAmount());
        }
        if (other.hasTollsAmount()) {
          setTollsAmount(other.getTollsAmount());
        }
        if (other.hasImprovementSurcharge()) {
          setImprovementSurcharge(other.getImprovementSurcharge());
        }
        if (other.hasTotalAmount()) {
          setTotalAmount(other.getTotalAmount());
        }
        if (other.hasCongestionSurcharge()) {
          setCongestionSurcharge(other.getCongestionSurcharge());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tistory.hskimsky.mapreduce.protobuf.YellowProto.Yellow) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string vendorID = 1;
      private java.lang.Object vendorID_ = "";
      /**
       * <code>optional string vendorID = 1;</code>
       */
      public boolean hasVendorID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string vendorID = 1;</code>
       */
      public java.lang.String getVendorID() {
        java.lang.Object ref = vendorID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          vendorID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string vendorID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVendorIDBytes() {
        java.lang.Object ref = vendorID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vendorID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string vendorID = 1;</code>
       */
      public Builder setVendorID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        vendorID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string vendorID = 1;</code>
       */
      public Builder clearVendorID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        vendorID_ = getDefaultInstance().getVendorID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string vendorID = 1;</code>
       */
      public Builder setVendorIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        vendorID_ = value;
        onChanged();
        return this;
      }

      // optional string tpepPickupDatetime = 2;
      private java.lang.Object tpepPickupDatetime_ = "";
      /**
       * <code>optional string tpepPickupDatetime = 2;</code>
       */
      public boolean hasTpepPickupDatetime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string tpepPickupDatetime = 2;</code>
       */
      public java.lang.String getTpepPickupDatetime() {
        java.lang.Object ref = tpepPickupDatetime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tpepPickupDatetime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tpepPickupDatetime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTpepPickupDatetimeBytes() {
        java.lang.Object ref = tpepPickupDatetime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tpepPickupDatetime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tpepPickupDatetime = 2;</code>
       */
      public Builder setTpepPickupDatetime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tpepPickupDatetime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tpepPickupDatetime = 2;</code>
       */
      public Builder clearTpepPickupDatetime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tpepPickupDatetime_ = getDefaultInstance().getTpepPickupDatetime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tpepPickupDatetime = 2;</code>
       */
      public Builder setTpepPickupDatetimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tpepPickupDatetime_ = value;
        onChanged();
        return this;
      }

      // optional string tpepDropoffDatetime = 3;
      private java.lang.Object tpepDropoffDatetime_ = "";
      /**
       * <code>optional string tpepDropoffDatetime = 3;</code>
       */
      public boolean hasTpepDropoffDatetime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string tpepDropoffDatetime = 3;</code>
       */
      public java.lang.String getTpepDropoffDatetime() {
        java.lang.Object ref = tpepDropoffDatetime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tpepDropoffDatetime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tpepDropoffDatetime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTpepDropoffDatetimeBytes() {
        java.lang.Object ref = tpepDropoffDatetime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tpepDropoffDatetime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tpepDropoffDatetime = 3;</code>
       */
      public Builder setTpepDropoffDatetime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tpepDropoffDatetime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tpepDropoffDatetime = 3;</code>
       */
      public Builder clearTpepDropoffDatetime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tpepDropoffDatetime_ = getDefaultInstance().getTpepDropoffDatetime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tpepDropoffDatetime = 3;</code>
       */
      public Builder setTpepDropoffDatetimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tpepDropoffDatetime_ = value;
        onChanged();
        return this;
      }

      // optional int32 passengerCount = 4;
      private int passengerCount_ ;
      /**
       * <code>optional int32 passengerCount = 4;</code>
       */
      public boolean hasPassengerCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 passengerCount = 4;</code>
       */
      public int getPassengerCount() {
        return passengerCount_;
      }
      /**
       * <code>optional int32 passengerCount = 4;</code>
       */
      public Builder setPassengerCount(int value) {
        bitField0_ |= 0x00000008;
        passengerCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 passengerCount = 4;</code>
       */
      public Builder clearPassengerCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        passengerCount_ = 0;
        onChanged();
        return this;
      }

      // optional float tripDistance = 5;
      private float tripDistance_ ;
      /**
       * <code>optional float tripDistance = 5;</code>
       */
      public boolean hasTripDistance() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float tripDistance = 5;</code>
       */
      public float getTripDistance() {
        return tripDistance_;
      }
      /**
       * <code>optional float tripDistance = 5;</code>
       */
      public Builder setTripDistance(float value) {
        bitField0_ |= 0x00000010;
        tripDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float tripDistance = 5;</code>
       */
      public Builder clearTripDistance() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tripDistance_ = 0F;
        onChanged();
        return this;
      }

      // optional string rateCodeID = 6;
      private java.lang.Object rateCodeID_ = "";
      /**
       * <code>optional string rateCodeID = 6;</code>
       */
      public boolean hasRateCodeID() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string rateCodeID = 6;</code>
       */
      public java.lang.String getRateCodeID() {
        java.lang.Object ref = rateCodeID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rateCodeID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rateCodeID = 6;</code>
       */
      public com.google.protobuf.ByteString
          getRateCodeIDBytes() {
        java.lang.Object ref = rateCodeID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rateCodeID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rateCodeID = 6;</code>
       */
      public Builder setRateCodeID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        rateCodeID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rateCodeID = 6;</code>
       */
      public Builder clearRateCodeID() {
        bitField0_ = (bitField0_ & ~0x00000020);
        rateCodeID_ = getDefaultInstance().getRateCodeID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rateCodeID = 6;</code>
       */
      public Builder setRateCodeIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        rateCodeID_ = value;
        onChanged();
        return this;
      }

      // optional string storeAndFwdFlag = 7;
      private java.lang.Object storeAndFwdFlag_ = "";
      /**
       * <code>optional string storeAndFwdFlag = 7;</code>
       */
      public boolean hasStoreAndFwdFlag() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string storeAndFwdFlag = 7;</code>
       */
      public java.lang.String getStoreAndFwdFlag() {
        java.lang.Object ref = storeAndFwdFlag_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          storeAndFwdFlag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string storeAndFwdFlag = 7;</code>
       */
      public com.google.protobuf.ByteString
          getStoreAndFwdFlagBytes() {
        java.lang.Object ref = storeAndFwdFlag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          storeAndFwdFlag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string storeAndFwdFlag = 7;</code>
       */
      public Builder setStoreAndFwdFlag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        storeAndFwdFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string storeAndFwdFlag = 7;</code>
       */
      public Builder clearStoreAndFwdFlag() {
        bitField0_ = (bitField0_ & ~0x00000040);
        storeAndFwdFlag_ = getDefaultInstance().getStoreAndFwdFlag();
        onChanged();
        return this;
      }
      /**
       * <code>optional string storeAndFwdFlag = 7;</code>
       */
      public Builder setStoreAndFwdFlagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        storeAndFwdFlag_ = value;
        onChanged();
        return this;
      }

      // optional string puLocationID = 8;
      private java.lang.Object puLocationID_ = "";
      /**
       * <code>optional string puLocationID = 8;</code>
       */
      public boolean hasPuLocationID() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string puLocationID = 8;</code>
       */
      public java.lang.String getPuLocationID() {
        java.lang.Object ref = puLocationID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          puLocationID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string puLocationID = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPuLocationIDBytes() {
        java.lang.Object ref = puLocationID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          puLocationID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string puLocationID = 8;</code>
       */
      public Builder setPuLocationID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        puLocationID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string puLocationID = 8;</code>
       */
      public Builder clearPuLocationID() {
        bitField0_ = (bitField0_ & ~0x00000080);
        puLocationID_ = getDefaultInstance().getPuLocationID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string puLocationID = 8;</code>
       */
      public Builder setPuLocationIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        puLocationID_ = value;
        onChanged();
        return this;
      }

      // optional string doLocationID = 9;
      private java.lang.Object doLocationID_ = "";
      /**
       * <code>optional string doLocationID = 9;</code>
       */
      public boolean hasDoLocationID() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string doLocationID = 9;</code>
       */
      public java.lang.String getDoLocationID() {
        java.lang.Object ref = doLocationID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          doLocationID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string doLocationID = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDoLocationIDBytes() {
        java.lang.Object ref = doLocationID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          doLocationID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string doLocationID = 9;</code>
       */
      public Builder setDoLocationID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        doLocationID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string doLocationID = 9;</code>
       */
      public Builder clearDoLocationID() {
        bitField0_ = (bitField0_ & ~0x00000100);
        doLocationID_ = getDefaultInstance().getDoLocationID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string doLocationID = 9;</code>
       */
      public Builder setDoLocationIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        doLocationID_ = value;
        onChanged();
        return this;
      }

      // optional string paymentType = 10;
      private java.lang.Object paymentType_ = "";
      /**
       * <code>optional string paymentType = 10;</code>
       */
      public boolean hasPaymentType() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string paymentType = 10;</code>
       */
      public java.lang.String getPaymentType() {
        java.lang.Object ref = paymentType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          paymentType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string paymentType = 10;</code>
       */
      public com.google.protobuf.ByteString
          getPaymentTypeBytes() {
        java.lang.Object ref = paymentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          paymentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string paymentType = 10;</code>
       */
      public Builder setPaymentType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        paymentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string paymentType = 10;</code>
       */
      public Builder clearPaymentType() {
        bitField0_ = (bitField0_ & ~0x00000200);
        paymentType_ = getDefaultInstance().getPaymentType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string paymentType = 10;</code>
       */
      public Builder setPaymentTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        paymentType_ = value;
        onChanged();
        return this;
      }

      // optional float fareAmount = 11;
      private float fareAmount_ ;
      /**
       * <code>optional float fareAmount = 11;</code>
       */
      public boolean hasFareAmount() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional float fareAmount = 11;</code>
       */
      public float getFareAmount() {
        return fareAmount_;
      }
      /**
       * <code>optional float fareAmount = 11;</code>
       */
      public Builder setFareAmount(float value) {
        bitField0_ |= 0x00000400;
        fareAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float fareAmount = 11;</code>
       */
      public Builder clearFareAmount() {
        bitField0_ = (bitField0_ & ~0x00000400);
        fareAmount_ = 0F;
        onChanged();
        return this;
      }

      // optional float extra = 12;
      private float extra_ ;
      /**
       * <code>optional float extra = 12;</code>
       */
      public boolean hasExtra() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional float extra = 12;</code>
       */
      public float getExtra() {
        return extra_;
      }
      /**
       * <code>optional float extra = 12;</code>
       */
      public Builder setExtra(float value) {
        bitField0_ |= 0x00000800;
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float extra = 12;</code>
       */
      public Builder clearExtra() {
        bitField0_ = (bitField0_ & ~0x00000800);
        extra_ = 0F;
        onChanged();
        return this;
      }

      // optional float mtaTax = 13;
      private float mtaTax_ ;
      /**
       * <code>optional float mtaTax = 13;</code>
       */
      public boolean hasMtaTax() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional float mtaTax = 13;</code>
       */
      public float getMtaTax() {
        return mtaTax_;
      }
      /**
       * <code>optional float mtaTax = 13;</code>
       */
      public Builder setMtaTax(float value) {
        bitField0_ |= 0x00001000;
        mtaTax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float mtaTax = 13;</code>
       */
      public Builder clearMtaTax() {
        bitField0_ = (bitField0_ & ~0x00001000);
        mtaTax_ = 0F;
        onChanged();
        return this;
      }

      // optional float tipAmount = 14;
      private float tipAmount_ ;
      /**
       * <code>optional float tipAmount = 14;</code>
       */
      public boolean hasTipAmount() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional float tipAmount = 14;</code>
       */
      public float getTipAmount() {
        return tipAmount_;
      }
      /**
       * <code>optional float tipAmount = 14;</code>
       */
      public Builder setTipAmount(float value) {
        bitField0_ |= 0x00002000;
        tipAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float tipAmount = 14;</code>
       */
      public Builder clearTipAmount() {
        bitField0_ = (bitField0_ & ~0x00002000);
        tipAmount_ = 0F;
        onChanged();
        return this;
      }

      // optional float tollsAmount = 15;
      private float tollsAmount_ ;
      /**
       * <code>optional float tollsAmount = 15;</code>
       */
      public boolean hasTollsAmount() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional float tollsAmount = 15;</code>
       */
      public float getTollsAmount() {
        return tollsAmount_;
      }
      /**
       * <code>optional float tollsAmount = 15;</code>
       */
      public Builder setTollsAmount(float value) {
        bitField0_ |= 0x00004000;
        tollsAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float tollsAmount = 15;</code>
       */
      public Builder clearTollsAmount() {
        bitField0_ = (bitField0_ & ~0x00004000);
        tollsAmount_ = 0F;
        onChanged();
        return this;
      }

      // optional float improvementSurcharge = 16;
      private float improvementSurcharge_ ;
      /**
       * <code>optional float improvementSurcharge = 16;</code>
       */
      public boolean hasImprovementSurcharge() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional float improvementSurcharge = 16;</code>
       */
      public float getImprovementSurcharge() {
        return improvementSurcharge_;
      }
      /**
       * <code>optional float improvementSurcharge = 16;</code>
       */
      public Builder setImprovementSurcharge(float value) {
        bitField0_ |= 0x00008000;
        improvementSurcharge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float improvementSurcharge = 16;</code>
       */
      public Builder clearImprovementSurcharge() {
        bitField0_ = (bitField0_ & ~0x00008000);
        improvementSurcharge_ = 0F;
        onChanged();
        return this;
      }

      // optional float totalAmount = 17;
      private float totalAmount_ ;
      /**
       * <code>optional float totalAmount = 17;</code>
       */
      public boolean hasTotalAmount() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional float totalAmount = 17;</code>
       */
      public float getTotalAmount() {
        return totalAmount_;
      }
      /**
       * <code>optional float totalAmount = 17;</code>
       */
      public Builder setTotalAmount(float value) {
        bitField0_ |= 0x00010000;
        totalAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float totalAmount = 17;</code>
       */
      public Builder clearTotalAmount() {
        bitField0_ = (bitField0_ & ~0x00010000);
        totalAmount_ = 0F;
        onChanged();
        return this;
      }

      // optional float congestionSurcharge = 18;
      private float congestionSurcharge_ ;
      /**
       * <code>optional float congestionSurcharge = 18;</code>
       */
      public boolean hasCongestionSurcharge() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>optional float congestionSurcharge = 18;</code>
       */
      public float getCongestionSurcharge() {
        return congestionSurcharge_;
      }
      /**
       * <code>optional float congestionSurcharge = 18;</code>
       */
      public Builder setCongestionSurcharge(float value) {
        bitField0_ |= 0x00020000;
        congestionSurcharge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float congestionSurcharge = 18;</code>
       */
      public Builder clearCongestionSurcharge() {
        bitField0_ = (bitField0_ & ~0x00020000);
        congestionSurcharge_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tistory.hskimsky.mapreduce.protobuf.Yellow)
    }

    static {
      defaultInstance = new Yellow(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tistory.hskimsky.mapreduce.protobuf.Yellow)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tistory_hskimsky_mapreduce_protobuf_Yellow_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tistory_hskimsky_mapreduce_protobuf_Yellow_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Yellow.proto\022\'com.tistory.hskimsky.map" +
      "reduce.protobuf\"\232\003\n\006Yellow\022\020\n\010vendorID\030\001" +
      " \001(\t\022\032\n\022tpepPickupDatetime\030\002 \001(\t\022\033\n\023tpep" +
      "DropoffDatetime\030\003 \001(\t\022\026\n\016passengerCount\030" +
      "\004 \001(\005\022\024\n\014tripDistance\030\005 \001(\002\022\022\n\nrateCodeI" +
      "D\030\006 \001(\t\022\027\n\017storeAndFwdFlag\030\007 \001(\t\022\024\n\014puLo" +
      "cationID\030\010 \001(\t\022\024\n\014doLocationID\030\t \001(\t\022\023\n\013" +
      "paymentType\030\n \001(\t\022\022\n\nfareAmount\030\013 \001(\002\022\r\n" +
      "\005extra\030\014 \001(\002\022\016\n\006mtaTax\030\r \001(\002\022\021\n\ttipAmoun" +
      "t\030\016 \001(\002\022\023\n\013tollsAmount\030\017 \001(\002\022\034\n\024improvem",
      "entSurcharge\030\020 \001(\002\022\023\n\013totalAmount\030\021 \001(\002\022" +
      "\033\n\023congestionSurcharge\030\022 \001(\002B6\n\'com.tist" +
      "ory.hskimsky.mapreduce.protobufB\013YellowP" +
      "roto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_tistory_hskimsky_mapreduce_protobuf_Yellow_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_tistory_hskimsky_mapreduce_protobuf_Yellow_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tistory_hskimsky_mapreduce_protobuf_Yellow_descriptor,
              new java.lang.String[] { "VendorID", "TpepPickupDatetime", "TpepDropoffDatetime", "PassengerCount", "TripDistance", "RateCodeID", "StoreAndFwdFlag", "PuLocationID", "DoLocationID", "PaymentType", "FareAmount", "Extra", "MtaTax", "TipAmount", "TollsAmount", "ImprovementSurcharge", "TotalAmount", "CongestionSurcharge", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
